scroll-tech/scroll-prover

- types/src/eth.rs
- types/src/lib.rs
Same as https://github.com/scroll-tech/roller/blob/main/src/lib.rs
> fix: add base64 encoding/decoding for zkProof marshalling/unmarshalling

- zkevm/src/circuit/builder.rs
related PR: https://github.com/scroll-tech/go-ethereum/pull/128
> fix(trace): add more opcode handlings

- .github/workflows/lint.yml
- Cargo.lock
- Makefile
- zkevm/Cargo.toml
- zkevm/src/circuit.rs
- zkevm/src/circuit/builder.rs
- zkevm/src/prover.rs
- zkevm/tests/integration.rs
- zkevm/tests/test_util.rs
WIP: zktrie (fail now: `MODE=multi RUST_LOG=trace MOCK_PROVE=true make test-super-trace`)
next: add dyn codehash (poseidon) implementation?
next: try real challenge api, but need https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1016
then: try real challenge api with aggregation circuit
> 1220 + developing features

- .github/workflows/release.yml
- Cargo.lock
- ffi/Cargo.toml
- ffi/src/lib.rs
- ffi/src/prove.rs
- ffi/src/verify.rs
- release.sh
Refer https://github.com/scroll-tech/scroll/pull/303
1. You can push a  git tag  and it will automatically create and upload the released package. ( I have already create the alpha-v1.0 )   
2. Move rust ffi codes of scroll here.
> feat: add ffi for scroll; add auto-release for tag

- .github/workflows/lint.yml
- .github/workflows/unit_test.yml
- Makefile
- README.md
- bin/src/mock_testnet.rs
- zkevm/configs/example_evm_accumulator.config
- zkevm/configs/verify_circuit.config
- zkevm/release.sh
- zkevm/src/lib.rs
1. Disable CI for `draft` PRs.
2. Rename `test_agg` to `test_aggregation_api` in shell scripts (Makefile and `release.sh`).
3. Format config JSON files with `jq`.
4. Delete tailed whitespaces (README).
5. Fix some typos.
> Small fixes

- zkevm/src/capacity_checker.rs
Reverts scroll-tech/scroll-zkevm#138
> Revert "add `Deserialize` & `Serialize` for `RowUsage`"

- prover/src/proof/chunk.rs
Testing with prover-test in scroll.
> Update `ChunkProof` for serialization

- prover/src/aggregator/prover.rs
- prover/src/aggregator/verifier.rs
- prover/src/inner/prover.rs
- prover/src/lib.rs
- prover/src/proof.rs
- prover/src/proof/batch.rs
- prover/src/proof/chunk.rs
- prover/src/proof/evm.rs
- prover/tests/aggregation_tests.rs
> feat: batch proof

- release.sh
Fix CI error
https://github.com/scroll-tech/scroll-prover/actions/runs/5746242289/job/15575412100
> fix: delete FFI related in release script

- Cargo.lock
- prover/Cargo.toml
- types/Cargo.toml
> Release `v0.5.6` with zkevm-circuits

- Cargo.lock
- prover/Cargo.toml
- types/Cargo.toml
> Upgrade zkevm-circuits to `v0.5.7`

- Cargo.lock
- prover/Cargo.toml
- types/Cargo.toml
Will run prover and verifier tests in scroll.
> Release `v0.5.8`

- Cargo.lock
- prover/Cargo.toml
- prover/src/proof/chunk.rs
- prover/src/zkevm/circuit/builder.rs
- prover/src/zkevm/prover.rs
- prover/tests/integration.rs
- types/Cargo.toml
- types/src/eth.rs
- Add optional `ChunkHash` to `ChunkProof`.
- Upgrade zkevm-circuits to support `start_l1_queue_index` for `ChunkHash`.
> Release `v0.5.13`

- prover/src/utils.rs
Panic if only return commit object as fallback when @HAOYUatHZ testing.
> Fix git-version bug

- Cargo.lock
- Cargo.toml
- prover/Cargo.toml
- types/Cargo.toml
Code is same with tag `v0.6.0`.
> Release `v0.6.0`

- prover/src/utils.rs
- prover/tests/integration.rs
- Check with `PARAMS_G2_SECRET_POWER` string in `load_params` function.
- Add `downsize_params` tests to `test_load_params`.
> check params.s_g2 after loading

- prover/src/aggregator/prover.rs
- prover/src/zkevm/prover.rs
Suppose to return null (nil) in scroll libzkp.
> feat: return vk from chunk and batch provers

- Cargo.lock
- prover/Cargo.toml
- prover/src/zkevm/capacity_checker.rs
- prover/src/zkevm/circuit/builder.rs
- types/Cargo.toml
> develop branch uses zkevm-circuits/decelop

- Cargo.lock
- prover/Cargo.toml
- prover/src/common/prover/chunk.rs
Related zkevm-circuits PR https://github.com/scroll-tech/zkevm-circuits/pull/860
- Check pairing on snark of super circuit.
- Upgrade zkevm-circuits.
> fix: check pairing after generates snark of super circuit

- download_setup.sh
> fix: replace params download URL to s3

- Cargo.lock
- integration/src/test_util/proof.rs
Related zkevm-circuits PR https://github.com/scroll-tech/zkevm-circuits/pull/964
> fix: delete `StorageTrace` when creates chunk proof (upgrade zkevm-circuits)

- .github/workflows/lint.yml
- .github/workflows/unit_test.yml
- Cargo.lock
- Cargo.toml
- Makefile
- README.md
- bin/Cargo.toml
- bin/src/prove.rs
- integration/Cargo.toml
- integration/tests/aggregation_tests.rs
- integration/tests/batch_tests.rs
- fix to use `workspace.package` and `workspace.dependencies`([features are additive](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table)).
- update README and CI.
- aggregation-test could pass.
> fix: update README and cleanup

- README.md
- docker/chunk-prover/gpu/Dockerfile
- docker/chunk-prover/gpu/docker-compose.yml
- docker/mock-testnet/gpu/Dockerfile
- docker/mock-testnet/gpu/docker-compose.yml
- scripts/gen_full_chunk_proofs.sh
- add a script `scripts/gen_full_chunk_proofs.sh` to generate `full_proof_1.json` for batch tests.
- add chunk-prover Dockerfile and `docker-compose.yml` (for GPU).
> fix: add chunk-prover docker and a script to generate full-proof for batch tests

- .env
- Cargo.lock
- Cargo.toml
- Makefile
- bin/src/chain_prover.rs
- bin/src/constants.rs
- bin/src/l2geth_client.rs
- bin/src/trace_prover.rs
- docker/chain-prover/gpu/docker-compose.yml
- integration/src/capacity_checker.rs
- integration/src/lib.rs
- integration/src/prove.rs
- integration/src/test_util.rs
- integration/tests/batch_tests.rs
- integration/tests/chunk_tests.rs
- integration/tests/e2e_tests.rs
- integration/tests/trace_dumper.py
- integration/tests/unit_tests.rs
> feat: chain prover with chunk/batch builder

- integration/tests/unit_tests.rs
This PR has induced a new unittest `test_evm_verifier_for_dumped_proof`, which is base on `test_evm_verifier`. It try to verify a dumped json file of bundle proof. User can put the proof json under corresponding `releae-xxx` directory and run
```
cargo test --release test_evm_verifier_for_dumped_proof -- --nocapture --ignored
```
so the test would test the proof against the evm bytecode in this release directory. Also it would dump the PI data and some other information in stdout
> [Feat] A new unittest for evm verifier
