scroll-tech/scroll-prover

Cargo.lock, Makefile, setup/src/main.rs, zkevm/Cargo.toml, zkevm/src/circuit.rs, zkevm/src/keygen.rs, zkevm/src/prover.rs, zkevm/src/utils.rs, zkevm/src/verifier.rs, zkevm/tests/integration.rs
1. allow read degree from env var （we may bring in aggregation circuit soon, so more flexible degree needed) 
2. better naming for some proving related vars
3. check of params file length when loading
=> some code improvements: 

types/Cargo.toml, zkevm/Cargo.toml
PR 42 has bump the depended mpt-circuit to a version with breaking changes in circuit,  which is a temporary fixing for encoiunting the witness with selfdestruct.
Now we decide to revert this updating in circuit to avoid impacts on integration tests.
=> bump the mpt circuit which revert a breaking change in circuit

types/src/eth.rs, zkevm/src/circuit/builder.rs
The base idea is pick codehash directly from trace rather than calculate it from codebytes, and build a correct code_db for witness generation:
1. For any call op, we pick codehash from sdb (we suppose the codehash never changed after contract is deployed)
2. For create, we can only pick codehash if the creation is success. However, we should notice that it is not need to put the code in db if deployment has failed (no one would call it again later)
3. For `EXTCODESIZE`, we has no way to get the codehash now. we need some update in l2geth to add the target account also being traced in `storageTrace` field. And we found that it is not need to update codeDB with codes in `EXTCODE` op
> ~However, evm circuit do not always respect the codehash provided from code_db, instead in `block_convert` …
=> Make poseidon codehash work temporarily

Dockerfile
Related `devops` issue - https://github.com/scroll-tech/devops/pull/18
=> fix: use docker image `rust-builder` with tag `nightly-2022-08-23` in Dockerfile

Cargo.lock, types/Cargo.toml, types/src/eth.rs, zkevm/Cargo.toml, zkevm/src/circuit.rs, zkevm/src/circuit/builder.rs
This PR use mpt and hash circuit from zkevm-circuit for stand alone testing.
It also switch the mpt witness generation from block trace into built-in generator completely.
No directly dependent of mpt circuit is required anymore.
The dynamic codehash interface is also induced to proving zkevm-circuit ablility of calculating poseidon codehash
=> Update mpt and poseidon circuit

Cargo.lock
We need to upgrade the implicit depended `halo2-mpt-circuit` with branch `goerli-0215-dual-hash`. The new commit completed some unfinished tunning for dual-codehash so we would not encounter constraint (lookup) failure inside zktrie circuit.
=> Upgrade mpt circuit

zkevm/src/circuit/builder.rs
There is a sanity check inside `trace_code` which ensure the code hash could not be updated once it has set. The current code is problematic for it check `nonce` or `balance` is non zero (so the account has been 'touched') and purpose code hash would be also updated under this condition. However, user can first transfer value into an account without create any code on it. And the sanity check will complain wrongly under this scene.
This PR change the sanity check to simply consider is there any code has been put into the account (so the `code_size` is not zero).
=> [Fix] sanity check for codehash updating

zkevm/src/utils.rs
Sometimes we should call `load_params()` from outside, so we need to public this `DEFAULT_SERDE_FORMAT`
https://github.com/scroll-tech/scroll/blob/develop/common/libzkp/impl/src/prove.rs#L20-L21
https://github.com/scroll-tech/scroll/blob/develop/common/libzkp/impl/src/verify.rs#L24-L25
=> fix: public DEFAULT_SERDE_FORMAT

Cargo.lock, bin/Cargo.toml, bin/src/mock_testnet.rs, bin/src/prove.rs, bin/src/setup.rs, bin/src/verify.rs, ffi/Cargo.toml, ffi/src/prove.rs, ffi/src/verify.rs, zkevm/Cargo.toml, zkevm/src/test_util.rs, zkevm/src/utils.rs, zkevm/tests/aggregation_tests.rs, zkevm/tests/integration.rs, zkevm/tests/snark_verifier_api.rs
After some investigation, `env_logger` seems to be hard to output logs to both stderr and a file, reference [this-comment](https://github.com/rust-cli/env_logger/issues/125#issuecomment-1406333500) (cannot set two `Target`s for a builder).
I fix to replace it with `log4rs`. It could write to both stderr and a file. But it cannot parse complicated `RUST_LOG` (only for simple ones as `RUST_LOG=info`).
The output logs as:
```
2023-06-05T16:36:13.734462+08:00 INFO zkevm::utils - git version prealpha-v2.0-24-gff7853e-modified
2023-06-05T16:36:13.734718+08:00 INFO aggregation_tests - created output dir agg_tests_output_multi_20230605_083613
2023-06-05T16:36:13.734763+08:00 INFO zkevm::test_util - using mode "multiple", testing with "./tests/traces/erc20/erc20_10_transfer.json" …
```
=> Replace `env_logger` with `log4rs` for logging to stderr and log file

prover/src/proof/chunk.rs
After testing, the generated `ChunkProof` is flatten (without nested node `proof`) as:
```
{
"storage_trace": "eyJyb290Qm ...",
"protocol": "eyJkb21haW ...",
"proof": "m9U8cCKb72 ...".
"instances": "W1tbMTMsMj ...",
"vk": "AAAAGAAA ..."
}
```
Related scroll commit https://github.com/scroll-tech/scroll/pull/689/commits/d4a89c780abc931ee1ba5994332d0ca2232728a7
=> fix: flatten `ChunkProof`

prover/src/common/verifier/evm.rs, prover/src/proof.rs, prover/src/proof/batch.rs, prover/tests/aggregation_tests.rs
- Fix `serialize_instance` as [encode_calldata in snark-verifier](https://github.com/scroll-tech/snark-verifier/blob/develop/snark-verifier/src/loader/evm/util.rs#L89).
- Add a function `assert_calldata` to `BatchProof`. It combines raw proof and instances to calldata, then assert equal with the result of `encode_calldata`.
=> Fix encoded calldata

Cargo.lock, prover/src/aggregator/verifier.rs, prover/src/common/prover/aggregation.rs, prover/src/common/prover/compression.rs, prover/src/common/prover/evm.rs, prover/src/config.rs, prover/src/zkevm/verifier.rs, prover/tests/aggregation_tests.rs, prover/tests/chunk_tests.rs
- ENV `SCROLL_PROVER_INNER_DEGREE` is used to set super-circuit degree (default as `20`).
- ENV `SCROLL_PROVER_ASSETS_DIR` is used for layer config files (default as `./configs`).
- Delete ENV `LAYER1_DEGREE` .. `LAYER4_DEGREE`, they are parsed from config file.
- Upgrade zkevm-circuits develop branch.
=> fix: add ENVs for layer config files

prover/src/proof.rs, prover/src/proof/batch.rs, prover/src/utils.rs, prover/tests/integration.rs
- Add a function `short_git_version` to get short commit version.
- Add this git version to both chunk and batch proofs.
=> fix: add `git_version` to both chunk and batch proofs

prover/src/zkevm/circuit/builder.rs
The `start_l1_queue_index` of chunk should be set to its first block's `start_l1_queue_index` instead of last block's `start_l1_queue_index`. 
This is related to https://github.com/scroll-tech/scroll-prover/pull/210.
=> Fix: use chunk's start_l1_queue_index

prover/src/zkevm/capacity_checker.rs, prover/src/zkevm/circuit.rs
the core idea here is we normalize real sub circuit row usages against 1M.
The row consumption is no longer real row num.
To avoid too many changes in chunk proposer.
=> normalize row usage: 1M means 100%

prover/src/aggregator/prover.rs, prover/src/proof/chunk.rs, prover/tests/aggregation_tests.rs
Related scroll PR https://github.com/scroll-tech/scroll/pull/807
- Add chunk-protocol when init aggregator prover, and check it with protocols in chunk-proofs when gen batch-proof.
- Dump chunk-protocol when dump chunk-proof (used to save chunk-protocol as asset file).
- Suppose if could also call `chunk_chunk_proofs` in go-prover of scroll, it could generate the clear error (to coordinator).
- Aggregation-tests could pass.
=> feat: dump chunk-protocol, and check it when gen batch proof

prover/src/common/verifier/evm.rs, prover/src/config.rs, prover/src/test_util.rs, prover/src/test_util/proof.rs
Make `test_util` functions could be passed into `output_dir` as None (not-saved).
=> Small refactor on `test_util` (will use for mass-testing)

prover/src/zkevm/circuit/builder.rs
We want to have `2*MAX_CALLDATA < MAX_RLP_ROWS` because each call data byte in a L2 tx takes two rows in the RLP circuit.
- add capacity for RLP circuit: 800k
- downsize the capacity of Tx circuit: 600k -> 350k since a batch can only have less than 200KB in the rollup contract.
=> Feat: add capacity for RLP circuit

prover/src/zkevm/capacity_checker.rs
in PR#249 we have removed [some cirtical code for estimating rows in bytecode/poseidon circuit](https://github.com/scroll-tech/scroll-prover/blob/3d33c6386de8e9f7275259a0ca063b005fc8b37d/prover/src/zkevm/capacity_checker.rs#L169) via ccc.
This PR try to resume the missing code.
=> [FIX] resume bytecode/poseidon circuit dedup in ccc

prover/src/common.rs, prover/src/lib.rs, prover/src/test_util.rs, prover/src/test_util/proof.rs
Suppose to call this function in mass-testing, and could use `CompressionCircuit` for further update.
=> fix: add test function `gen_and_verify_normal_proof`

integration/src/test_util.rs, integration/tests/chunk_tests.rs, integration/tests/inner_tests.rs, integration/tests/integration.rs, integration/tests/mock_tests.rs
- delete hardcode of `new.json` trace in chunk-tests (which causes wrong test on chunk-234914).
- set `./tests/extra_traces/new.json` as default test trace (it could also be set by ENV `TRACE_PATH`).
- move inner-prove and move-prove to separate files.
=> Refactor integration tests

README.md
Related issue https://github.com/scroll-tech/scroll-prover/issues/284
=> fix: add `solc` install to README

integration/configs/layer2.config, integration/configs/layer3.config, integration/configs/layer4.config
- layer2: increase deg from 2^24 to 2^25 and reduce 2 advice polys to 1.
- layer3: increase deg from 2^20 to 2^21 and increase snark-verifier advice polys from 59 to 63.
- layer4: reduce num of lookup advice columns from 2 to 1.
Final verification cost is around 370k.
=> Agg circuit parameters tunning 

Cargo.lock, Makefile, bin/src/chain_prover.rs, bin/src/l2geth_client.rs
work with https://github.com/scroll-tech/go-ethereum/pull/836
```
export SCROLL_MAINNET_CURIE_BLOCK=1
make chain-prover 2>&1 | tee chain.log
```
=> feat: chain prover force curie mode

integration/src/lib.rs, integration/src/prove.rs, integration/src/verifier.rs
The config for `layer6` has been optimized so it is now different with `layer4`. Notice [the `Verifier` for aggregator always make use a config from layer4](https://github.com/scroll-tech/zkevm-circuits/blob/c534681bf35554357bf80cf565f8fdbaa33eec9b/prover/src/aggregator/verifier.rs#L43), it cause an error while loading the vkey generated in bundle circuit (with config of `layer6`).
This has exlained why [this commit](https://github.com/scroll-tech/scroll-prover/commit/527476b10f9255a33b98b7d1853cb6dfaa0c908a) has to rename the loaded vkey to make it pass e2e test: it would fail if it actually load the vkey for bundle circuit (configured by `layer6`) but would pass if it just load vkey for batch circuit again. Also, for verifier verifing for final layer (bundle) do not use the vkey it …
=> [Refactor] Verifier for compression circuit
